services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sesen-api
    volumes:
      - ${PWD}/.env:/.env
    ports:
      - 80:80
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    container_name: sesen-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DBNAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: on-failure:3

  redis:
    image: redis/redis-stack:latest
    container_name: sesen-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-volume:/data
    restart: on-failure:3

volumes:
  postgres-volume:
  redis-volume:
