apiVersion: v1
kind: Secret
metadata:
  name: sesen-api-secret
  namespace: sesen
type: Opaque
stringData:
  DB_USER: '${DB_USER}'
  DB_PASS: '${DB_PASS}'
  DB_HOST: '${DB_HOST}'
  DB_PORT: '${DB_PORT}'
  DB_DBNAME: '${DB_DBNAME}'
  DB_SSLMODE: '${DB_SSLMODE}'
  DB_TIMEZONE: '${DB_TIMEZONE}'
  JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
