apiVersion: v1
kind: Service
metadata:
  name: sesen-api-service
  namespace: sesen
spec:
  type: ClusterIP
  selector:
    app: sesen-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
